apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-operator
  namespace: default
  labels:
    app: multitool-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: multitool-operator
  template:
    metadata:
      labels:
        app: multitool-operator
    spec:
      serviceAccountName: multitool-operator
      securityContext:
        runAsUser:
          1000
      containers:
      - envFrom:
          - configMapRef:
              name: multitool-operator
        name: operator
        image: djkormo/python-k8s-multitool:0.0.18
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        #imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
#        livenessProbe:
#          httpGet:
#            path: /healthz
#            port: 8080
#          initialDelaySeconds: 10
#          periodSeconds: 30
#          timeoutSeconds: 10
#          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
