apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: multitool-operator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multitool-operator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: multitool-operator