apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projectnetworkpolicies.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: ProjectNetworkPolicy
    listKind: ProjectNetworkPolicyList
    plural: projectnetworkpolicies
    singular: projectnetworkpolicy
    shortNames:
      - prnetpol
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}