apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projectrbacs.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: ProjectRBAC
    listKind: ProjectRBACList
    plural: projectrbacs
    singular: projectrbac
    shortNames:
      - prrbac
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}