apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.djkormo.github
spec:
  group: djkormo.github
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
    shortNames:
      - pr
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}